const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const orderSchema = new Schema({
  id: Number,
  documentId: Number,
  itemId: String,
  assortment: String,
  code: String,
  client: String,
  dateInsert: String,
  dateOfPay: String,
  dateOfRealisation: String,
  dateOfAcceptation: String,
  signature: String,
  symbol: String,
  kind: String,
  type: String,
  details: String,
  closed: Boolean,
  documentStatus: Number,
  trader: String,
  deliveryAddress: String,
  details: String,
  transport: String,
  numberOfDocumentInvoice: Number,
  invoice: String,
  quantity: Number,
  price: Number,
  grossWeight: Number,
  netWeight: Number,
  netValue: String,
  sleeve: Number,
  stretchColor: String,
  stretchThickness: Number,
  color1: String,
  color2: String,
  color3: String,
  glue: String,
  numberOfColors: String,
  printName: String,
  productCode: String,
  roller: String,
  tapeColor: String,
  tapeLong: Number,
  tapeThickness: Number,
  tapeWidth: Number
});

const Order = mongoose.model("order", orderSchema);
module.exports = Order;
